# Generated by Django 4.2.2 on 2023-06-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to=''),
        ),
    ]
